services:
  postgres:
    image: postgres:15
    container_name: user-db
    restart: always
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "8006:5432"
    volumes:
      - pgdata:/var/lib/postgresql/user/data

volumes:
  pgdata: